### ISSUE TITLE
will this package be on atmosphere?

### ISSUE THREAD

**Issue by apvlv** [copleykj/socialize-follow#2]
How i can install it without atmosphere?

Thank you!

**Comment by copleykj** [comment]
The intent is to have this on atmosphere in the future. At this point I've not added it there because of work planned around followers requesting permission to follow. Since requesting is also a feature of the friendships package, the plan is to factor out the requesting so that requesting can be implemented in many other packages including work on such things as event listings that I haven't started working on yet.

For now the package can be used by cloning it into the packages directory of your app.
